import * as fs from 'fs';

const raw = fs.readFileSync('scripts/seed_analytical_tables.sql', 'utf8');

function extractRows(rawSql, startComment, nextComment) {
  const startIdx = rawSql.indexOf(startComment);
  const valIdx = rawSql.indexOf('VALUES', startIdx);
  const endIdx = nextComment ? rawSql.indexOf(nextComment, valIdx) : rawSql.length;
  const block = rawSql.substring(valIdx + 6, endIdx);
  const semiIdx = block.lastIndexOf(';');
  const clean = block.substring(0, semiIdx).trim();
  const lines = clean.split('\n').map(l => l.trim().replace(/,$/, '')).filter(l => l.length > 0);
  return lines;
}

const pfRows = extractRows(raw, '-- STEP 3: Seed project_financials', '-- STEP 4: Seed project_progress');
const ppRows = extractRows(raw, '-- STEP 4: Seed project_progress', '-- STEP 5: Seed risk_scores');
const rsRows = extractRows(raw, '-- STEP 5: Seed risk_scores', '-- STEP 6: Seed duplicate_matches');
const dmRows = extractRows(raw, '-- STEP 6: Seed duplicate_matches', '-- STEP 7: Validation Query');

if (pfRows.length !== 100 || ppRows.length !== 100 || rsRows.length !== 100 || dmRows.length !== 20) {
  console.error('Row count mismatch!', { pf: pfRows.length, pp: ppRows.length, rs: rsRows.length, dm: dmRows.length });
  process.exit(1);
}

let out = '-- ====================================================================\n';
out += '-- MPLADS INTELLIGENCE: Safe Analytical Tables Seed Migration\n';
out += '-- Target Database: Supabase PostgreSQL (Administrative Execution)\n';
out += '-- Target File: scripts/seed_analytical_tables_safe.sql\n';
out += '-- Records: 100 project_financials, 100 project_progress, 100 risk_scores, 20 duplicate_matches\n';
out += '--\n';
out += '-- SAFETY & IDEMPOTENCY GUARANTEES:\n';
out += '-- 1. NO DELETIONS: Existing tables and records are never deleted or truncated.\n';
out += '-- 2. STRICT IDEMPOTENCY: Re-executing this script will NOT create duplicate rows.\n';
out += '-- 3. SCHEMA RESPECT: Missing UNIQUE constraints on foreign key columns (project_id)\n';
out += '--    are identified; idempotency is achieved via "WHERE NOT EXISTS" without creating\n';
out += '--    unsolicited constraints on existing tables.\n';
out += '-- 4. FOREIGN KEY VALIDATION: Every project_id and matched_project_id is strictly\n';
out += '--    validated against existing projects.id rows via INNER JOINs.\n';
out += '-- 5. MINIMAL RLS: Row-Level Security remains enabled on all tables.\n';
out += '--    Only the minimal SELECT policy required for frontend viewing is ensured.\n';
out += '--    NO broad public/anonymous INSERT or UPDATE policies are created.\n';
out += '-- 6. UNTOUCHED TABLES: Core operational tables (projects, payments, risk_alerts,\n';
out += '--    investigations, investigation_notes, investigation_requests,\n';
out += '--    investigation_responses, users, system_settings) are NOT modified.\n';
out += '-- ====================================================================\n\n';

out += '-- STEP 1: Ensure Minimum Required RLS SELECT Policies for Public/Anonymous Read Access\n';
out += '-- (Note: Administrative execution via Supabase SQL Editor bypasses RLS for seeding.\n';
out += '--  Broad public INSERT / UPDATE policies are strictly forbidden and NOT created.)\n';
out += 'DO $$\nBEGIN\n';
out += '  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = \'project_financials\' AND policyname = \'Allow public select project_financials\') THEN\n';
out += '    CREATE POLICY "Allow public select project_financials" ON project_financials FOR SELECT USING (true);\n';
out += '  END IF;\n\n';
out += '  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = \'project_progress\' AND policyname = \'Allow public select project_progress\') THEN\n';
out += '    CREATE POLICY "Allow public select project_progress" ON project_progress FOR SELECT USING (true);\n';
out += '  END IF;\n\n';
out += '  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = \'risk_scores\' AND policyname = \'Allow public select risk_scores\') THEN\n';
out += '    CREATE POLICY "Allow public select risk_scores" ON risk_scores FOR SELECT USING (true);\n';
out += '  END IF;\n\n';
out += '  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = \'duplicate_matches\' AND policyname = \'Allow public select duplicate_matches\') THEN\n';
out += '    CREATE POLICY "Allow public select duplicate_matches" ON duplicate_matches FOR SELECT USING (true);\n';
out += '  END IF;\n';
out += 'END $$;\n\n';

out += '-- ====================================================================\n';
out += '-- STEP 2: Seed project_financials (100 rows)\n';
out += '-- Constraint note: project_financials has no unique constraint on project_id.\n';
out += '-- Idempotency: WHERE NOT EXISTS prevents duplicates if re-run.\n';
out += '-- Integrity: JOIN projects p ON p.id = v.project_id validates foreign key.\n';
out += '-- ====================================================================\n';
out += 'INSERT INTO project_financials (project_id, sanctioned_amount, expenditure, financial_utilization)\n';
out += 'SELECT\n';
out += '  v.project_id::uuid,\n';
out += '  v.sanctioned_amount::numeric,\n';
out += '  v.expenditure::numeric,\n';
out += '  v.financial_utilization::numeric\n';
out += 'FROM (\n  VALUES\n';
out += pfRows.map((r, i) => {
  return '    ' + r;
}).join(',\n');
out += '\n) AS v(project_id, sanctioned_amount, expenditure, financial_utilization)\n';
out += 'JOIN projects p ON p.id = v.project_id::uuid\n';
out += 'WHERE NOT EXISTS (\n';
out += '  SELECT 1 FROM project_financials pf WHERE pf.project_id = v.project_id::uuid\n';
out += ');\n\n';

out += '-- ====================================================================\n';
out += '-- STEP 3: Seed project_progress (100 rows)\n';
out += '-- Constraint note: project_progress has no unique constraint on project_id.\n';
out += '-- Idempotency: WHERE NOT EXISTS prevents duplicates if re-run.\n';
out += '-- Integrity: JOIN projects p ON p.id = v.project_id validates foreign key.\n';
out += '-- ====================================================================\n';
out += 'INSERT INTO project_progress (project_id, physical_progress, delay_days, remarks)\n';
out += 'SELECT\n';
out += '  v.project_id::uuid,\n';
out += '  v.physical_progress::integer,\n';
out += '  v.delay_days::integer,\n';
out += '  v.remarks::text\n';
out += 'FROM (\n  VALUES\n';
out += ppRows.map((r, i) => {
  return '    ' + r;
}).join(',\n');
out += '\n) AS v(project_id, physical_progress, delay_days, remarks)\n';
out += 'JOIN projects p ON p.id = v.project_id::uuid\n';
out += 'WHERE NOT EXISTS (\n';
out += '  SELECT 1 FROM project_progress pp WHERE pp.project_id = v.project_id::uuid\n';
out += ');\n\n';

out += '-- ====================================================================\n';
out += '-- STEP 4: Seed risk_scores (100 rows)\n';
out += '-- Constraint note: risk_scores has no unique constraint on project_id.\n';
out += '-- Idempotency: WHERE NOT EXISTS prevents duplicates if re-run.\n';
out += '-- Integrity: JOIN projects p ON p.id = v.project_id validates foreign key.\n';
out += '-- Methodology: Rule-Based Risk Engine, prototype-1.0\n';
out += '-- ====================================================================\n';
out += 'INSERT INTO risk_scores (\n';
out += '  project_id,\n';
out += '  total_risk_score,\n';
out += '  progress_expenditure_score,\n';
out += '  model_name,\n';
out += '  model_version,\n';
out += '  prediction,\n';
out += '  top_risk_factors,\n';
out += '  recommendation,\n';
out += '  risk_level,\n';
out += '  cost_anomaly_score,\n';
out += '  payment_anomaly_score,\n';
out += '  delay_score,\n';
out += '  duplicate_similarity_score,\n';
out += '  input_timestamp\n';
out += ')\n';
out += 'SELECT\n';
out += '  v.project_id::uuid,\n';
out += '  v.total_risk_score::numeric,\n';
out += '  v.progress_expenditure_score::numeric,\n';
out += '  v.model_name::text,\n';
out += '  v.model_version::text,\n';
out += '  v.prediction::text,\n';
out += '  v.top_risk_factors::text[],\n';
out += '  v.recommendation::text,\n';
out += '  v.risk_level::text,\n';
out += '  v.cost_anomaly_score::numeric,\n';
out += '  v.payment_anomaly_score::numeric,\n';
out += '  v.delay_score::numeric,\n';
out += '  v.duplicate_similarity_score::numeric,\n';
out += '  v.input_timestamp::timestamptz\n';
out += 'FROM (\n  VALUES\n';
out += rsRows.map((r, i) => {
  return '    ' + r;
}).join(',\n');
out += '\n) AS v(\n';
out += '  project_id,\n';
out += '  total_risk_score,\n';
out += '  progress_expenditure_score,\n';
out += '  model_name,\n';
out += '  model_version,\n';
out += '  prediction,\n';
out += '  top_risk_factors,\n';
out += '  recommendation,\n';
out += '  risk_level,\n';
out += '  cost_anomaly_score,\n';
out += '  payment_anomaly_score,\n';
out += '  delay_score,\n';
out += '  duplicate_similarity_score,\n';
out += '  input_timestamp\n';
out += ')\n';
out += 'JOIN projects p ON p.id = v.project_id::uuid\n';
out += 'WHERE NOT EXISTS (\n';
out += '  SELECT 1 FROM risk_scores rs WHERE rs.project_id = v.project_id::uuid\n';
out += ');\n\n';

out += '-- ====================================================================\n';
out += '-- STEP 5: Seed duplicate_matches (20 rows)\n';
out += '-- Constraint note: duplicate_matches has no unique constraint on (project_id, matched_project_id).\n';
out += '-- Idempotency: WHERE NOT EXISTS prevents duplicates if re-run.\n';
out += '-- Integrity: JOIN projects on both project_id and matched_project_id validates relationships.\n';
out += '-- ====================================================================\n';
out += 'INSERT INTO duplicate_matches (project_id, matched_project_id, similarity_score, status)\n';
out += 'SELECT\n';
out += '  v.project_id::uuid,\n';
out += '  v.matched_project_id::uuid,\n';
out += '  v.similarity_score::numeric,\n';
out += '  v.status::text\n';
out += 'FROM (\n  VALUES\n';
out += dmRows.map((r, i) => {
  return '    ' + r;
}).join(',\n');
out += '\n) AS v(project_id, matched_project_id, similarity_score, status)\n';
out += 'JOIN projects p1 ON p1.id = v.project_id::uuid\n';
out += 'JOIN projects p2 ON p2.id = v.matched_project_id::uuid\n';
out += 'WHERE NOT EXISTS (\n';
out += '  SELECT 1 FROM duplicate_matches dm\n';
out += '  WHERE dm.project_id = v.project_id::uuid\n';
out += '    AND dm.matched_project_id = v.matched_project_id::uuid\n';
out += ');\n\n';

out += '-- ====================================================================\n';
out += '-- STEP 6: VERIFICATION QUERIES (Requirements 12, 13, 14)\n';
out += '-- ====================================================================\n\n';

out += '-- Query 1: Detailed Table Counts and Target Validation (Requirement 12)\n';
out += 'SELECT\n';
out += '  \'projects\' AS table_name, count(*) AS actual_count, 100 AS expected_count, (count(*) = 100) AS is_valid FROM projects\n';
out += 'UNION ALL\n';
out += 'SELECT \'project_financials\', count(*), 100, (count(*) = 100) FROM project_financials\n';
out += 'UNION ALL\n';
out += 'SELECT \'project_progress\', count(*), 100, (count(*) = 100) FROM project_progress\n';
out += 'UNION ALL\n';
out += 'SELECT \'risk_scores\', count(*), 100, (count(*) = 100) FROM risk_scores\n';
out += 'UNION ALL\n';
out += 'SELECT \'payments\', count(*), 300, (count(*) = 300) FROM payments\n';
out += 'UNION ALL\n';
out += 'SELECT \'duplicate_matches\', count(*), 20, (count(*) = 20) FROM duplicate_matches\n';
out += 'UNION ALL\n';
out += 'SELECT \'risk_alerts\', count(*), 27, (count(*) = 27) FROM risk_alerts\n';
out += 'UNION ALL\n';
out += 'SELECT \'investigations\', count(*), 11, (count(*) = 11) FROM investigations\n';
out += 'UNION ALL\n';
out += 'SELECT \'investigation_requests\', count(*), 11, (count(*) = 11) FROM investigation_requests\n';
out += 'UNION ALL\n';
out += 'SELECT \'investigation_responses\', count(*), 11, (count(*) = 11) FROM investigation_responses\n';
out += 'UNION ALL\n';
out += 'SELECT \'users\', count(*), 4, (count(*) = 4) FROM users\n';
out += 'UNION ALL\n';
out += 'SELECT \'system_settings\', count(*), 3, (count(*) = 3) FROM system_settings;\n\n';

out += '-- Query 2: Horizontal Count Summary (Requirement 12)\n';
out += 'SELECT\n';
out += '  (SELECT count(*) FROM projects) AS count_projects,                               -- Expected: 100\n';
out += '  (SELECT count(*) FROM project_financials) AS count_project_financials,           -- Expected: 100\n';
out += '  (SELECT count(*) FROM project_progress) AS count_project_progress,               -- Expected: 100\n';
out += '  (SELECT count(*) FROM risk_scores) AS count_risk_scores,                         -- Expected: 100\n';
out += '  (SELECT count(*) FROM payments) AS count_payments,                               -- Expected: 300\n';
out += '  (SELECT count(*) FROM duplicate_matches) AS count_duplicate_matches,             -- Expected: 20\n';
out += '  (SELECT count(*) FROM risk_alerts) AS count_risk_alerts,                         -- Expected: 27\n';
out += '  (SELECT count(*) FROM investigations) AS count_investigations,                   -- Expected: 11\n';
out += '  (SELECT count(*) FROM investigation_requests) AS count_investigation_requests,   -- Expected: 11\n';
out += '  (SELECT count(*) FROM investigation_responses) AS count_investigation_responses, -- Expected: 11\n';
out += '  (SELECT count(*) FROM users) AS count_users,                                     -- Expected: 4\n';
out += '  (SELECT count(*) FROM system_settings) AS count_system_settings;                 -- Expected: 3\n\n';

out += '-- Query 3: Orphan Dependency Checks (Requirement 13) - All Expected to be 0\n';
out += 'SELECT\n';
out += '  (SELECT count(*) FROM project_financials pf LEFT JOIN projects p ON pf.project_id = p.id WHERE p.id IS NULL) AS orphan_project_financials,\n';
out += '  (SELECT count(*) FROM project_progress pp LEFT JOIN projects p ON pp.project_id = p.id WHERE p.id IS NULL) AS orphan_project_progress,\n';
out += '  (SELECT count(*) FROM risk_scores rs LEFT JOIN projects p ON rs.project_id = p.id WHERE p.id IS NULL) AS orphan_risk_scores,\n';
out += '  (SELECT count(*) FROM duplicate_matches dm LEFT JOIN projects p ON dm.project_id = p.id WHERE p.id IS NULL) AS orphan_duplicate_matches_source,\n';
out += '  (SELECT count(*) FROM duplicate_matches dm LEFT JOIN projects p ON dm.matched_project_id = p.id WHERE p.id IS NULL) AS orphan_duplicate_matches_target;\n\n';

out += '-- Query 4: Project-to-Analytical 1:1 Cardinality Check (Requirement 14)\n';
out += 'SELECT\n';
out += '  count(*) AS total_projects,                                                      -- Expected: 100\n';
out += '  count(*) FILTER (WHERE financials_count = 1) AS projects_with_1_financials,     -- Expected: 100\n';
out += '  count(*) FILTER (WHERE progress_count = 1) AS projects_with_1_progress,         -- Expected: 100\n';
out += '  count(*) FILTER (WHERE risk_count = 1) AS projects_with_1_risk_score,           -- Expected: 100\n';
out += '  count(*) FILTER (WHERE financials_count != 1 OR progress_count != 1 OR risk_count != 1) AS projects_with_cardinality_mismatch -- Expected: 0\n';
out += 'FROM (\n';
out += '  SELECT\n';
out += '    p.id,\n';
out += '    (SELECT count(*) FROM project_financials pf WHERE pf.project_id = p.id) AS financials_count,\n';
out += '    (SELECT count(*) FROM project_progress pp WHERE pp.project_id = p.id) AS progress_count,\n';
out += '    (SELECT count(*) FROM risk_scores rs WHERE rs.project_id = p.id) AS risk_count\n';
out += '  FROM projects p\n';
out += ') sub;\n';

fs.writeFileSync('scripts/seed_analytical_tables_safe.sql', out);
console.log('Successfully written scripts/seed_analytical_tables_safe.sql! Bytes:', out.length);
