import { ModelMetadata } from './types';

export const ACTIVE_ML_MODELS: ModelMetadata[] = [
  {
    name: 'Isolation Forest Anomaly Engine',
    modelType: 'Unsupervised Randomized Ensemble (100 iTrees)',
    version: 'v1.4.2',
    trainingDate: '2026-01-15',
    featureVersion: 'FV-7D-NORM',
    status: 'Active',
    accuracyOrAUC: 'AUC-ROC: 0.932 (Cross-Validated)',
    description: 'Detects multi-dimensional structural anomalies across expenditure, disbursement velocity, and cost benchmark ratios without supervisory bias.',
    inferenceLatencyMs: 4.2,
  },
  {
    name: 'XGBoost Risk Classifier',
    modelType: 'Gradient Boosted Decision Trees (GBDT)',
    version: 'v2.0.1',
    trainingDate: '2026-02-01',
    featureVersion: 'FV-10D-EXTENDED',
    status: 'Active',
    accuracyOrAUC: 'Accuracy: 91.4% | F1-Score: 0.892',
    description: 'Evaluates risk probability and severity mapping using gradient boosting over 8 tuned decision trees with logistic margin calibration.',
    inferenceLatencyMs: 3.8,
  },
  {
    name: 'Milestone Delay Forecaster',
    modelType: 'Gradient Boosted Regressor',
    version: 'v2.1.0',
    trainingDate: '2026-02-10',
    featureVersion: 'FV-TEMPORAL-V3',
    status: 'Active',
    accuracyOrAUC: 'MAE: 8.4 Days | R²: 0.865',
    description: 'Projects remaining completion timeline and estimated schedule slippage based on physical execution velocity and historical lag.',
    inferenceLatencyMs: 2.9,
  },
  {
    name: 'Sentence-BERT Semantic Matcher',
    modelType: 'Dense Vector Cosine Matcher & NLP Embedder',
    version: 'v1.5.0',
    trainingDate: '2026-01-20',
    featureVersion: 'EMB-32D-CIVIC',
    status: 'Active',
    accuracyOrAUC: 'Top-1 Accuracy: 96.1%',
    description: 'Subword tokenization and contextual semantic vector distance to identify duplicate schemes, overlapping work orders, and repetitive bills across departments.',
    inferenceLatencyMs: 5.1,
  },
  {
    name: 'TreeSHAP Explainability Kernel',
    modelType: 'Cooperative Game Theory Shapley Attribution',
    version: 'v1.1.0',
    trainingDate: '2026-02-01',
    featureVersion: 'SHAP-EXACT-TREE',
    status: 'Active',
    accuracyOrAUC: 'Full Additivity Proof Verified',
    description: 'Decomposes continuous composite risk prediction into exact additive points attributable to each specific operational data dimension.',
    inferenceLatencyMs: 3.5,
  },
];
